#! /usr/bin/php
<?php /* -*- mode:php -*- */

require_once ("/opt/slimstk/slimstkcmdext.php");
slimstk_init ();

$args = array ();
$config = slimstk_install_site ($args);

$ssl_files = find_ssl_files ($config['url_name']);
foreach (explode (" ", $ssl_files) as $token) {
	$token = trim ($token);
	if (preg_match ('/key$/', $token)) {
		$key = $token;
	} else if (preg_match ('/crt$/', $token)) {
		$crt = $token;
	} else if (preg_match ('/pem$/', $token)) {
		$pem = $token;
	}
}

$config_file = fopen ("config.py", "w");
fprintf ($config_file, "keyfile = \"%s\"\n", $key);
fprintf ($config_file, "crt = \"%s\"\n", $crt);
fprintf ($config_file, "pem = \"%s\"\n", $pem);
fclose ($config_file);
