#! /usr/bin/php
<?php /* -*- mode:php -*- */

require_once ("/opt/slimstk/slimstkcmdext.php");
slimstk_init ();

$args = array ();
$config = slimstk_install_site ($args);

$ssl_files = find_ssl_files ($config['url_name']);

$config_file = fopen ("config.py", "w");
fwrite ($config_file, "keyfile = \"$ssl_files[0]\"\n");
fwrite ($config_file, "crt = \"$ssl_files[1]\"\n");
fwrite ($config_file, "pem = \"$ssl_files[2]\"\n");
fclose ($config_file);
